name: met_annot_enhancer_env
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - python==3.8
  - pandas
  - matchms
  - tqdm
  - plotly
  - pip
  - pyyaml
  - chembl_webresource_client
  - jupyter_pivottablejs
  - pip :
    - opentree
