
# default.yaml

---
# parameters

job:
  - job_id: enterjobidhere # The path were you want your folder to be placed
  
paths:
  - gnps_job_path: /Users/pma/Dropbox/Research_UNIGE/Projets/Ongoing/MEMO/ # The path were you want your folder to be placed
  - project_name: GNPS_3 # The name you want to give to your project, output resulst in data_out/project_name
  - metadata_path: /Users/pma/210523_lotus_dnp_metadata.csv  # Path to your spectral library file
  - db_file_path: db_spectra/LOTUS_DNP_ISDB.mgf # Path to the metadata of the spectral file
  - adducts_pos_path: data_loc/db_prepared_pos.tsv.gz # Path to the adducts file in pos mode
  - adducts_neg_path: data_loc/db_prepared_neg.tsv.gz # Path to the adducts file in neg mode

spectral_match_params:
  - parent_mz_tol: 0.01 # the parent mass tolerance to use for spectral matching (in Da)
  - msms_mz_tol: 0.01 # the msms mass tolerance to use for spectral matching (in Da)
  - min_cos: 0.3 # the minimal cosine to use for spectral matching
  - min_peaks: 8 # the minimal matching peaks number to use for spectral matching

repond_params:
  - Run_line_x_line: True # Set to True if multiple biosource in your dataset
  - Top_N_Sample: 2 # Max number of contributors to take into account for taxo reponderation (Run_line_x_line parameter), set to 0 for all
  - top_to_output: 1 # Top X for final ouput
  - ppm_tol: 0.1 # ppm tol to be used for ms1 match
  - polarity: 'Pos' # ion mode you are working with (pos or neg)
  - organism_header: 'species_cof' # Mandatory (Run_line_x_line parameter) 
  - sampletype_header: 'sample_type' # Optional (Run_line_x_line parameter)
  - use_post_taxo: True # Set True if you want to use rank after taxonomical reweighting for consensus chemical class determination, else set to False
  - top_N_chemical_consistency: 5 # Top N to use for chemical consistency 
  - file_extension: '.mzXML' # MS filename extension (a common pattern in all your filenames) Check the header of your feature table if you dont know (Run_line_x_line parameter)
  - msfile_suffix: '' # MS filename additional chracters (a common pattern in all your filenames) Check the header of your feature table if you dont know (Run_line_x_line parameter)
