
# default.yaml

---
# parameters
job:
  - job_id: 'f8c981fe7fed4b0482667a76731f5b65' # '250536f4cb3e4f159e5ef67a3d024fac' # The GNPS id of the Job you want to annotate. 
  - gnps_job_path: data_in/ # The path were you want your folder to be placed
  - project_name: 'pma_job' #'ISDB_annot_LP_plantfungi_set' # The name you want to give to your project

